project:
  type: website
  output-dir: docs

website:
  title: "Ethan Larimore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - text: Resume
        href: assets/Github_Ethan_Larimore_Resume.pdf
        target: _blank

format:
  html:
    theme: midnight
    css: custom.scss
    toc: true
    page-layout: full



